Flex merge feeds
ibi-group/gtfs-lib pull request #1
Opened 2023-11-21 17:05 UTC by philip-cline

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing

### Description

Flex updates to support flex feed merging in datatools.

2023-11-21 17:05 UTC, philip-cline commented
This PR has been reopened in the forked repository

2023-11-27 22:34 UTC, binh-dam-ibigroup requested changes
Please cleanup some `try` blocks and spelling, please.

2023-11-27 22:34 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/StopTime.java
> +            if (connection != null) DbUtils.closeQuietly(connection);
Put the result of `dataSource.getConnection()` as a "resource" or close within the `finally` statement of the `try` block that calls this method, and remove the `finally` block (and probably the entire corresponding `try` statement) from this method.

2023-11-27 22:34 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/util/GeoJsonUtil.java
> +     * Extract the locations from Geo Json.
Fix the GeoJSON spelling (see https://geojson.org/) and update the other comments too.
```suggestion
     * Extract the locations from GeoJSON.
```

2023-11-27 22:34 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/util/GeoJsonUtil.java
> +            String message = "Unable to extract GeoJson features (or none are available) from " + entry.getName();
Fix the "GeoJSON" spelling.

2023-11-27 22:34 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/GTFSTest.java
> -                new RecordExpectation("stop_id", "123")
Also delete trailing comma on previous line

2023-11-28 10:42 UTC, br648 commented on src/main/java/com/conveyal/gtfs/util/GeoJsonUtil.java
> +            String message = "Unable to extract GeoJson features (or none are available) from " + entry.getName();
@binh-dam-ibigroup Do you think I should update all classes and methods as well?

2023-11-28 14:26 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/util/GeoJsonUtil.java
> +            String message = "Unable to extract GeoJson features (or none are available) from " + entry.getName();
Maybe in another PR that could be against upstream?

2023-11-28 14:38 UTC, binh-dam-ibigroup approved these changes

2023-11-28 14:38 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/util/GeoJsonUtil.java
> +        if (features == null) {
Might be able to use a ternary here and in the next function.

2024-01-30 14:23 UTC, miles-grant-ibigroup requested changes
Are we sure this PR is good to go? Since stop areas has been re-renamed

2024-02-05 14:24 UTC, br648 commented
> Are we sure this PR is good to go? Since stop areas has been re-renamed

@miles-grant-ibigroup The thinking is to get this merged albeit with the wrong naming. Once this aspect of the flex spec is set-in-stone, then update across the board.

2024-02-05 14:28 UTC, miles-grant-ibigroup approved these changes
Gotcha. Great fixes thanks!

2024-02-05 14:47 UTC, merged