improved shared stops error messages
ibi-group/gtfs-lib pull request #5
Opened 2023-12-25 20:29 UTC by miles-grant-ibigroup

### Checklist

- [x] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [x] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [x] The description lists all applicable issues this PR seeks to resolve
- [x] The description lists any configuration setting(s) that differ from the default settings
- [x] All tests and CI builds passing
- [ ] The description lists all relevant PRs included in this release _(remove this if not merging to master)_
- [ ] Code coverage does not significantly worsen (ideally it improves) _(remove this if not merging to master)_

### Description

Some of the shared stops error messages were confusing! Or didn't reflect reality. This PR resolves this issue.

2023-12-27 18:10 UTC, philip-cline approved these changes
Love it. Good repo choice

2024-01-02 10:41 UTC, br648 requested changes

2024-01-02 10:41 UTC, br648 commented on src/main/java/com/conveyal/gtfs/error/NewGTFSErrorType.java
> +    SHARED_STOP_GROUP_MUTLIPLE_PRIMARY_STOPS(Priority.HIGH, "A shared-stop group has multiple primary stops."),
I think this is a good opportunity to address this typo as noted by Phil in your other PR.

2024-01-02 13:58 UTC, br648 approved these changes

2024-01-02 14:39 UTC, merged