Fares V2
ibi-group/gtfs-lib pull request #8
Opened 2024-08-19 12:09 UTC by br648

### Checklist

- [ ] Appropriate branch selected _(all PRs must first be merged to `dev` before they can be merged to `master`)_
- [ ] Any modified or new methods or classes have helpful JavaDoc and code is thoroughly commented
- [ ] The description lists all applicable issues this PR seeks to resolve
- [ ] The description lists any configuration setting(s) that differ from the default settings
- [ ] All tests and CI builds passing
- [ ] The description lists all relevant PRs included in this release _(remove this if not merging to master)_
- [ ] Code coverage does not significantly worsen (ideally it improves) _(remove this if not merging to master)_

### Description

Update to include fares v2 based on design:

https://docs.google.com/document/d/1EBMoxfXscPhFWyrn4fyGR6foQ7JGBWvMWeodrvo7DPw/edit

2026-04-14 15:13 UTC, miles-grant-ibigroup requested changes
So much boilerplate wow... this looks really good! Just 2 small things

2026-04-14 15:13 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> -     */
What happened here? This is important functionality

2026-04-14 15:13 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/gtfs/model/Entity.java
> +    public static final String SEPARATOR = "§";
This still feels like a bit of a rough hack. Could we try `U+001E` or `U+001F`?

2026-04-14 15:13 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/gtfs/model/Entity.java
> +         * The main entry point into an Entity.Loader. Interprets each row of a CSV file within a zip file as a single
Nice catch

2026-04-14 15:13 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +public class CsvReaderUtil {
I see now what happened... Why are there all these new methods? Some of them seem quite coupled too

2026-04-15 06:47 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/Table.java
> -     */
Functionality moved to `CsvReaderUtil.java`

2026-04-15 07:57 UTC, br648 commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +public class CsvReaderUtil {
So it can still meet existing CSV reading requirements along with the fares v2 merging requirements. I have combined a couple of methods so there is now one less method. Hooray!

2026-04-15 09:22 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/Entity.java
> +    public static final String SEPARATOR = "§";
Updated to use: U+001E.

2026-04-15 15:28 UTC, miles-grant-ibigroup commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +public class CsvReaderUtil {
does this mean that the feed merge feature works for fares v2?!

2026-04-15 15:29 UTC, miles-grant-ibigroup approved these changes
This looks great! Because of the scope of these changes I couldn't review as carefully as I could for a smaller PR, but everything seems to work well and the changes look clean

2026-04-16 06:50 UTC, br648 commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +public class CsvReaderUtil {
Yes. It is only fares v2 that requires merging i.e stop areas into stops and route networks in routes.

2026-04-16 22:28 UTC, binh-dam-ibigroup reviewed
First round of comments just from reading some of the files. More to come.

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLUtil.java
> +        return new ArrayList<>(Arrays.asList(intArg(ID_ARG), intArg(LIMIT_ARG), intArg(OFFSET_ARG)));
Replace `new ArrayList<>(Arrays.asList(<args>))` with `Lists.newArrayList(<args>)` (It looks like we do need an `ArrayList` in `buildArgs(addOns)`)

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsFaresV2Schema.java
> +    private static final GraphQLObjectType areaType = newObject().name(AREA_TYPE_NAME)
In src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java, you reformatted the builders so that the `.name()` call appears on its own line. You should do the same in this file too.

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLUtil.java
> +    public static GraphQLFieldDefinition createFieldDefinition(String name, GraphQLType graphQLType, String tableName) {
Nit: consider a shorter name, for example: `fieldDefinition`, `declareField`, or even just `field`.

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
> +        .field(MapFetcher.field("route_color"))
Reuse the field constants that you also use in `EntityPopulator` for the route type.

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
> +        .field(MapFetcher.field("parent_station"))
Reuse the field constants that you also use in `EntityPopulator` for the stop type.

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java
> +            result.fareLegRules = load(Table.FARE_LEG_RULES); // ref areas
Do we need the comment?

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/loader/JDBCTableReader.java
> +
Remove blank line.

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/Area.java
> +            area.id = row + 1; // offset line number by 1 to account for 0-based row index
Is this to obtain a non-zero id-as-number for internal use?

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/Area.java
> +
Remove blank line

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/Entity.java
> +    // Record Separator is a non-printable ASCII character that is unlikely to appear in GTFS data.
Use `/**` comment.

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/FareLegJoinRule.java
> +
Remove blank line.

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/FareLegRule.java
> +
Remove extra blank line.

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/FareLegRule.java
> +
Remove blank line

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/FareMedia.java
> +
Remove extra blank lines

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/FareMedia.java
> +
Remove blank line

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/FareTransferRule.java
> +
Remove extra blank lines

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/dto/RouteDTO.java
> +
Remove blank line

2026-04-16 22:28 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java
>          assertTimeout(Duration.ofMillis(TEST_TIMEOUT), () -> {
Extract a constant for `Duration.ofMillis(TEST_TIMEOUT)`.

2026-04-20 20:09 UTC, binh-dam-ibigroup requested changes
Just a few refactor requests for now, and I still need to run the code with the other stuff,
mainly split `CsvReaderUtil.getCsvReaderFromMergedFiles`, inling a few `return`, and cleaning up dead code. The other suggestions and comment additions would be nice to have.

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/Route.java
> +            return Collections.emptyMap();
Add a comment that we aren't returning a map unless all mappings aren't generating an error (that's the intent, correct?). Do the same for the analog method in Stop.java.

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/StopArea.java
> +            getRefField(AREA_ID_NAME, true, feed.areas);
What happens here if the referential integrity fails?

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/model/TimeFrame.java
> +                // An empty value is considered the start of the day (00:00:00).
Say in the comment that the value is expressed in seconds past midnight, local time (do that in line 68 too).

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +        return csvReader;
Inline the `return` statement in each of the if/else blocks.

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +        boolean isStops
I'd recommend writing two versions of this method, one where `isStop` is false, the other where `isStop` is true. (`isStop` i checked 4 times in this implementation).

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +        InputStream zipInputStream = zipFile.getInputStream(entry);
Add a comment about how these streams will be closed.

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +        String[] headers = csvReader.getHeaders();
Is it possible to reuse `hasExpectedNumberOfColumns` here?

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterFaresV2Test.java
> +        assertThatSqlQueryYieldsRowCount(getColumnsForId(1, table));
Reuse `TestUtils.assertThatSqlQueryYieldsZeroRows` (that method appears unused otherwise).

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterFaresV2Test.java
> +    public static void setUpClass() throws SQLException {
The public qualifiers are not necessary.

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/GTFSFaresV2Test.java
> +        TestUtils.FileTestCase[] fileTestCases = {
This test should be a `@ParameterizedTest`, and these should be the part of the `@MethodSource` for that test. (I know that the old tests use this inverted layout.)

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/GTFSFaresV2Test.java
> +            TestUtils.dropDB(testDBName);
Should we reuse `faresDBName` here and have it be dropped `@AfterEach` and created `@BeforeEach`?

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/TestUtils.java
> +    private static final String JDBC_URL = "jdbc:postgresql://localhost";
This constant seems unused.

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/TestUtils.java
> +    public static void assertResultValue(ResultSet resultSet, String field, Matcher matcher) throws SQLException {
This method seems unused.

2026-04-20 20:09 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/TestUtils.java
> +    public static ResultSet getResultSetForId(DataSource dataSource, String namespace, int id, Table table, String... columns) throws SQLException {
This method seems unused.

2026-04-21 07:30 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/StopArea.java
> +            getRefField(AREA_ID_NAME, true, feed.areas);
A `ReferentialIntegrityError` is flagged. Processing is not halted.

2026-04-21 08:14 UTC, br648 commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +        String[] headers = csvReader.getHeaders();
The error message would be misleading bc of the line number.

2026-04-21 13:15 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/Area.java
> +            area.id = row + 1; // offset line number by 1 to account for 0-based row index
This is in almost every entity. I've just copied it.

2026-04-21 14:01 UTC, br648 commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLUtil.java
> +        return new ArrayList<>(Arrays.asList(intArg(ID_ARG), intArg(LIMIT_ARG), intArg(OFFSET_ARG)));
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:01 UTC, br648 commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsFaresV2Schema.java
> +    private static final GraphQLObjectType areaType = newObject().name(AREA_TYPE_NAME)
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:11 UTC, br648 commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLUtil.java
> +    public static GraphQLFieldDefinition createFieldDefinition(String name, GraphQLType graphQLType, String tableName) {
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:11 UTC, br648 commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
> +        .field(MapFetcher.field("route_color"))
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:11 UTC, br648 commented on src/main/java/com/conveyal/gtfs/graphql/GraphQLGtfsSchema.java
> +        .field(MapFetcher.field("parent_station"))
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:11 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/JdbcGtfsLoader.java
> +            result.fareLegRules = load(Table.FARE_LEG_RULES); // ref areas
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:11 UTC, br648 commented on src/main/java/com/conveyal/gtfs/loader/JDBCTableReader.java
> +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:12 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/Area.java
> +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:12 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/Entity.java
> +    // Record Separator is a non-printable ASCII character that is unlikely to appear in GTFS data.
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:12 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/FareLegJoinRule.java
> +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:12 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/FareLegRule.java
> +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:12 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/FareLegRule.java
> +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:12 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/FareMedia.java
> +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:12 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/FareTransferRule.java
> +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:12 UTC, br648 commented on src/test/java/com/conveyal/gtfs/dto/RouteDTO.java
> +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:12 UTC, br648 commented on src/test/java/com/conveyal/gtfs/graphql/GTFSGraphQLTest.java
>          assertTimeout(Duration.ofMillis(TEST_TIMEOUT), () -> {
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:13 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/Route.java
> +            return Collections.emptyMap();
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:13 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/TimeFrame.java
> +                // An empty value is considered the start of the day (00:00:00).
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:13 UTC, br648 commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +        return csvReader;
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:13 UTC, br648 commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +        boolean isStops
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:13 UTC, br648 commented on src/main/java/com/conveyal/gtfs/util/CsvReaderUtil.java
> +        InputStream zipInputStream = zipFile.getInputStream(entry);
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:14 UTC, br648 commented on src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterFaresV2Test.java
> +        assertThatSqlQueryYieldsRowCount(getColumnsForId(1, table));
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:14 UTC, br648 commented on src/test/java/com/conveyal/gtfs/loader/JDBCTableWriterFaresV2Test.java
> +    public static void setUpClass() throws SQLException {
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:14 UTC, br648 commented on src/test/java/com/conveyal/gtfs/GTFSFaresV2Test.java
> +            TestUtils.dropDB(testDBName);
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:14 UTC, br648 commented on src/test/java/com/conveyal/gtfs/TestUtils.java
> +    public static void assertResultValue(ResultSet resultSet, String field, Matcher matcher) throws SQLException {
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:14 UTC, br648 commented on src/test/java/com/conveyal/gtfs/TestUtils.java
> +    public static ResultSet getResultSetForId(DataSource dataSource, String namespace, int id, Table table, String... columns) throws SQLException {
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:14 UTC, br648 commented on src/test/java/com/conveyal/gtfs/TestUtils.java
> +    private static final String JDBC_URL = "jdbc:postgresql://localhost";
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 14:15 UTC, br648 commented on src/main/java/com/conveyal/gtfs/model/FareMedia.java
> +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/changes/5444da3f3cf93b740788bdecbc7bdc9ac6eb9e54

2026-04-21 15:23 UTC, br648 commented on src/test/java/com/conveyal/gtfs/GTFSFaresV2Test.java
> +        TestUtils.FileTestCase[] fileTestCases = {
Fixed in: github.com/ibi-group/gtfs-lib/pull/8/commits/a54a7376a1a0a735f38b9b558c1e2191677f7338

2026-04-22 21:59 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/GTFSFaresV2Test.java
>          ZipFile zip = new ZipFile(outZip);
Move this code to the actual test.

2026-04-22 22:03 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/GTFSFaresV2Test.java
> +    void canDoRoundTripLoadAndWriteToZipFile(ZipFile zip, TestUtils.FileTestCase fileTestCase) throws IOException {
Remove the `zip` parameter, and move the creation of the zip file in this function.

2026-04-22 22:04 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/TestUtils.java
> +            return "FileTestCase{" +
Use `String.format`.

2026-04-22 22:09 UTC, binh-dam-ibigroup requested changes
One more small change in the tests, then I will approve. The other changes seem fine and appear to work with datatools-server.

2026-04-23 07:18 UTC, br648 commented on src/test/java/com/conveyal/gtfs/TestUtils.java
> +            return "FileTestCase{" +
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/commits/10ef4e07485b9860b3c75fa7ac300775afe6b994

2026-04-23 07:21 UTC, br648 commented on src/test/java/com/conveyal/gtfs/GTFSFaresV2Test.java
> +    void canDoRoundTripLoadAndWriteToZipFile(ZipFile zip, TestUtils.FileTestCase fileTestCase) throws IOException {
It seems inefficent to create the same output zip ten times, so I've moved the code to the setup instead. I've also made sure the file is deleted once done. Update: https://github.com/ibi-group/gtfs-lib/pull/8/commits/10ef4e07485b9860b3c75fa7ac300775afe6b994

2026-04-23 07:21 UTC, br648 commented on src/test/java/com/conveyal/gtfs/GTFSFaresV2Test.java
>          ZipFile zip = new ZipFile(outZip);
Fixed in: https://github.com/ibi-group/gtfs-lib/pull/8/commits/10ef4e07485b9860b3c75fa7ac300775afe6b994

2026-04-23 13:52 UTC, binh-dam-ibigroup commented on src/test/java/com/conveyal/gtfs/GTFSFaresV2Test.java
> +    void canDoRoundTripLoadAndWriteToZipFile(ZipFile zip, TestUtils.FileTestCase fileTestCase) throws IOException {
Nice, that works too.

2026-04-23 14:41 UTC, binh-dam-ibigroup approved these changes
Thank you for the changes!

2026-04-23 14:51 UTC, merged